#
# FileName:     Makefile
# Author: 		8ucchiman
# CreatedDate:  2023-10-06 17:15:19
# LastModified: 2023-02-03 21:27:40 +0900
# Reference: 	https://qiita.com/chibi929/items/b8c5f36434d5d3fbfa4a
# Description:	---
#


.PHONY: clean run debug build

run:
	codon run sample.py


build:
	codon build -release -exe sample.py

debug:


clean:
